version: '3.8'

services:
  web:
    image: php:8.0-apache
    container_name: php_web
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    networks:
      - my_network

  db:
    image: mysql:8.0  # Обновлено для поддержки ARM
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
